[workspace]
authors = ["Ben Moss <bmoss40@bloomberg.net>"]
channels = ["conda-forge"]
name = "caddy-demo"
platforms = ["osx-arm64", "linux-64", "osx-64"]
version = "0.1.0"

[tasks]
start = { cmd = "honcho start" }

[dependencies]
caddy = ">=2.10.0,<3"
jupyterlab = ">=4.4.5,<5"
dash = ">=3.2.0,<4"
numpy = ">=2.3.2,<3"
pandas = ">=2.3.1,<3"
honcho = ">=2.0.0,<3"
